url: "https://test-stand.gb.ru/gateway/login"
login: "kitty89"
pass: "61d96a3985"
owner: "notMe"
url_post: "https://test-stand.gb.ru/api/posts"
title: "TESTING"
descr: "DESCRIPTION OF TESTING"
cont: "my content"
token: "34d94713de90534fef86c2d61225e710"